### ISSUE TITLE
Perform Technical review

### ISSUE THREAD

**Issue by Revathyvenugopal162** [ansys/scade-apitools#14]
Technical review comments
- [x] Update the files to new guidelines #13
- [x] Add contributors and code owners files #13
- [x] update the documentation to Autoapi docs #13
- [x] #15
- [x] Fix the precommit
- [x] Add pyproject.toml file #10
- [x] fix action #13
- [x] Update configuration for the documentation #13
- [x] Remove requirements Folder #10
- [x] Update readme #13
- [ ] Documentation review
- [x] update dependencies
- [ ] Add license headers #13 temporarily disabled
- [ ] Check the test coverage
- [x] remove the extension directory specific to scade-apitools and add it to make file #13
- [x] remove autosummary #13
